# Generated by Django 6.0.2 on 2026-02-19 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True)),
                ('base_form', models.CharField(max_length=100)),
                ('past_simple', models.CharField(max_length=100)),
                ('past_participle', models.CharField(max_length=100)),
                ('translation', models.JSONField(default=dict)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DailyLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_lessons', to=settings.AUTH_USER_MODEL)),
                ('verbs', models.ManyToManyField(related_name='lessons', to='core.verb')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='LessonContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_sentences', models.JSONField(default=list)),
                ('quiz_questions', models.JSONField(default=list)),
                ('fill_gap_exercise', models.JSONField(default=dict)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='core.dailylesson')),
                ('verb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.verb')),
            ],
        ),
    ]
