# Generated by Django 6.0.2 on 2026-02-19 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verb',
            name='conjugations',
            field=models.JSONField(default=dict),
        ),
    ]
