# Generated by Django 6.0.2 on 2026-02-20 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_verb_conjugations'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylesson',
            name='user_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
